In [16]:
import pandas as pd 
import numpy as np

In [31]:
shots_df = pd.read_csv('../data/afl_shots.csv')
shots_df.head()

,Unnamed: 0,player_id,player,Season,Round,Team,Opposition,Distance,Pocket,ShotType,x,y,Score,xScore
0,0,1407800,Jaidyn Stephenson,2021,1,North Melbourne,Port Adelaide,30 to <40 m,Pocket,Set Position,29.0,-26,1,3.4
1,1,1407800,Jaidyn Stephenson,2021,3,North Melbourne,Western Bulldogs,30 to <40 m,Corridor,Set Position,34.0,-11,6,4.6
2,2,1407800,Jaidyn Stephenson,2021,3,North Melbourne,Western Bulldogs,15 to <30 m,Pocket,Set Position,13.0,-21,6,3.6
3,3,1407800,Jaidyn Stephenson,2021,5,North Melbourne,Geelong,40 to <50 m,Pocket,Set Position,25.0,37,0,2.1
4,4,1407800,Jaidyn Stephenson,2021,5,North Melbourne,Geelong,40 to <50 m,Corridor,Set Position,45.0,19,1,3.0

In [14]:
jez_df = shots_df[shots_df['player_id']== '230055']
jez_df[(jez_df['Season'] == 2022) & (jez_df['Round'] == 18) & (jez_df['xScore'] == 1.3)].head()

,Unnamed: 0,player_id,player,Season,Round,Team,Opposition,Distance,Pocket,ShotType,x,y,Score,xScore
26125,26125,230055,Jeremy Cameron,2022,18,Geelong,Carlton,15 to <30 m,Pocket,General Play,9.0,-26,6,1.3

In [24]:
jez_df['dist_to_goal'] = np.sqrt((jez_df['x'])**2 + (jez_df['y'])**2)
jez_df['dist_to_l_post'] = np.sqrt((jez_df['x'])**2 + (3.2 - jez_df['y'])**2)
jez_df['dist_to_r_post'] = np.sqrt((jez_df['x'])**2 + (-3.2 - jez_df['y'])**2)
jez_df['angle_to_goal'] = (np.arccos((jez_df['dist_to_l_post']**2 + jez_df['dist_to_r_post']**2 - 6.4**2) / (2 * jez_df['dist_to_l_post'] * jez_df['dist_to_r_post'])) * (180/np.pi)
)
jez_df[(jez_df['Season'] == 2022) & (jez_df['Round'] == 18) & (jez_df['xScore'] == 1.3)].head()

,Unnamed: 0,player_id,player,Season,Round,Team,Opposition,Distance,Pocket,ShotType,x,y,Score,xScore,dist_to_goal,dist_to_l_post,dist_to_r_post,angle_to_goal
26125,26125,230055,Jeremy Cameron,2022,18,Geelong,Carlton,15 to <30 m,Pocket,General Play,9.0,-26,6,1.3,27.513633,30.555523,24.512038,4.410674

In [26]:
print(np.arccos((9**2 + 27.513633**2 - 26**2) / (2 * 9 * 27.513633)) * (180/np.pi))

70.90650790563647

In [34]:
shots_df['dist_to_goal'] = np.sqrt((shots_df['x'])**2 + (shots_df['y'])**2)
shots_df['dist_to_l_post'] = np.sqrt((shots_df['x'])**2 + (3.2 - shots_df['y'])**2)
shots_df['dist_to_r_post'] = np.sqrt((shots_df['x'])**2 + (-3.2 - shots_df['y'])**2)
shots_df['angle_to_goal'] = (np.arccos((shots_df['dist_to_l_post']**2 + shots_df['dist_to_r_post']**2 - 6.4**2) / (2 * shots_df['dist_to_l_post'] * shots_df['dist_to_r_post'])) * (180/np.pi)
)
shots_df['set_shot_flag'] = np.where(shots_df["ShotType"] == 'Set Position', 1, 0)
shots_df_clean = shots_df.drop(columns = ['Distance', 'Pocket','dist_to_l_post', 'dist_to_r_post', 'ShotType', 'Unnamed: 0'])
shots_df_clean.head()

,player_id,player,Season,Round,Team,Opposition,x,y,Score,xScore,dist_to_goal,angle_to_goal,set_shot_flag
0,1407800,Jaidyn Stephenson,2021,1,North Melbourne,Port Adelaide,29.0,-26,1,3.4,38.948684,7.022218,1
1,1407800,Jaidyn Stephenson,2021,3,North Melbourne,Western Bulldogs,34.0,-11,6,4.6,35.735137,9.746961,1
2,1407800,Jaidyn Stephenson,2021,3,North Melbourne,Western Bulldogs,13.0,-21,6,3.6,24.698178,7.897790,1
3,1407800,Jaidyn Stephenson,2021,5,North Melbourne,Geelong,25.0,37,0,2.1,44.654227,4.611205,1
4,1407800,Jaidyn Stephenson,2021,5,North Melbourne,Geelong,45.0,19,1,3.0,48.846699,6.911919,1

In [ ]:
shots_df_clean.to_csv('../data/processed_shots.csv', index=False)